In [1]:
import os
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
blob = "s3://s3-common-dev20220705170301665500000003/qtracker_demo/data/01_model_input"

In [3]:
df = pd.read_csv(os.path.join(blob, "datasetchurn.csv"), sep=";")

In [4]:
df.head()

,id_client,genre,espace_client_web,assurance_vie,banque_principale,anciennete_mois,compte_epargne,credit_autres,cartes_bancaires,compte_courant,...,var_31,var_32,var_33,var_34,var_35,var_36,var_37,var_38,branche,churn
0,3463,H,0.0,0.0,0.0,37.0,1.0,consommation,medium,1,...,13545.535937,12243.785415,12140.590245,9013.777747,11604.261036,16390.415593,14631.204899,23988.305931,NORD-OUEST,0
1,1869,H,0.0,1.0,1.0,72.0,1.0,consommation,premium,inconnu,...,14014.989673,15508.546834,17547.988381,15470.524076,17537.628474,17410.472648,21258.908987,21554.411100,NORD-OUEST,0
2,3760,H,0.0,0.0,0.0,3.0,1.0,NaN,medium,0,...,17239.846026,19479.322456,21343.802381,24084.291026,25823.493343,25839.829752,25587.814976,29736.376226,NORD-OUEST,0
3,3820,H,1.0,1.0,0.0,72.0,1.0,consommation,medium,1,...,9229.470887,11935.244779,11014.748509,11791.353542,16354.051367,15449.967495,21149.789933,29211.314803,NORD-OUEST,0
4,1463,F,0.0,0.0,0.0,4.0,1.0,permanent,medium,0,...,9008.641700,5875.342745,6101.742525,8026.508871,10361.246523,10575.966610,6714.625315,9101.978017,NORD-OUEST,1

In [5]:
df = df.dropna()

In [6]:
cat_features = [
    "genre",
    "espace_client_web",
    "assurance_vie",
    "banque_principale",
    "compte_epargne",
    "credit_autres",
    "cartes_bancaires",
    "compte_courant",
    "compte_joint",
    "PEA",
    "assurance_auto",
    "assurance_habitation",
    "credit_immo",
    "type",
    "compte_titres",
    "methode_contact",
    "segment_client",
]

enc = OneHotEncoder(drop="if_binary", sparse_output=False, handle_unknown="ignore")
df_cat = enc.fit_transform(df[cat_features])
df_cat = pd.DataFrame(data=df_cat, columns=enc.get_feature_names_out(), index=df.index)

In [7]:
df_num = df[[col for col in df.columns if col not in cat_features]]

In [8]:
df_final = pd.concat([df_cat, df_num], axis=1)

In [9]:
df_final.describe()

,genre_H,espace_client_web_1.0,assurance_vie_1.0,banque_principale_1.0,compte_epargne_1.0,credit_autres_bail,credit_autres_consommation,credit_autres_permanent,cartes_bancaires_basic,cartes_bancaires_medium,...,var_30,var_31,var_32,var_33,var_34,var_35,var_36,var_37,var_38,churn
count,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,...,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000,1549.000000
mean,0.493221,0.201420,0.415107,0.238864,0.902518,0.097482,0.394448,0.508070,0.338928,0.512589,...,10869.440773,12174.730591,13585.627851,15075.917817,16653.683176,18430.310117,20220.114718,22040.013042,24095.597595,0.336992
std,0.500116,0.401191,0.492900,0.426527,0.296709,0.296709,0.488890,0.500096,0.473498,0.500003,...,5717.614921,6132.181412,6663.001611,7230.557992,7689.416566,8408.396175,8865.035302,9437.177444,10149.392701,0.472835
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,752.417136,864.801297,1427.838791,1588.694401,1650.264772,1866.593101,2575.874124,3246.049376,3237.877887,0.000000
25%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,6876.438805,7941.198678,8865.041248,9944.162131,11054.477070,12354.592745,13764.821681,15118.993771,16957.500678,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,9989.817484,11201.175881,12568.225599,13879.546937,15519.516907,17248.931690,18997.969442,20833.155901,22582.102480,0.000000
75%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,13879.515944,15591.009038,17339.140714,19240.716575,21407.310441,23164.791442,25499.272174,27579.146533,29762.235441,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,51631.046359,52168.475128,53365.481384,55138.005795,60420.738152,65341.742998,65581.846151,66054.499607,74069.493748,1.000000

In [10]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df_final, test_size=0.33, shuffle=True, random_state=123)

In [11]:
columns_to_keep = [
"churn",
"genre_H",
"espace_client_web_1.0",
"assurance_vie_1.0",
"banque_principale_1.0",
"compte_epargne_1.0",
"credit_autres_bail",
"credit_autres_consommation",
"credit_autres_permanent",
"cartes_bancaires_basic",
"cartes_bancaires_medium",
"cartes_bancaires_premium",
"compte_courant_0",
"compte_courant_1",
"compte_courant_inconnu",
"compte_joint_0",
"compte_joint_1",
"compte_joint_inconnu",
"PEA_0",
"PEA_1",
"PEA_inconnu",
"assurance_auto_0",
"assurance_auto_1",
"assurance_auto_inconnu",
"assurance_habitation_0",
"assurance_habitation_1",
"assurance_habitation_inconnu",
"credit_immo_0",
"credit_immo_1",
"credit_immo_inconnu",
"type_pro",
"compte_titres_1.0",
"methode_contact_courrier",
"methode_contact_mail",
"methode_contact_sms",
"methode_contact_telephone",
"segment_client_A1",
"segment_client_A2",
"segment_client_A3",
"segment_client_A4",
"segment_client_B1",
"segment_client_B2",
"segment_client_B3",
"segment_client_B4",
"segment_client_C1",
"segment_client_C2",
"segment_client_C3",
"segment_client_C4",
"segment_client_D1",
"segment_client_D2",
"segment_client_D3",
"anciennete_mois",
"agios_6mois",
"interet_compte_epargne_total",
"age",
"var_0",
"var_18",
"var_19",
"var_20",
"var_37",
"var_38"
]

In [12]:
!pwd

/home/pgodbillot/projects/modularization-quinten/qtracker/notebooks

In [13]:
df_train[columns_to_keep].to_csv(os.path.join("../data/01_model_input", "train.final_dataset.csv"), index=False)
df_test[columns_to_keep].to_csv(os.path.join("../data/01_model_input", "test.final_dataset.csv"), index=False)
df_test[columns_to_keep].to_csv(os.path.join("../data/01_model_input", "inference.final_dataset.csv"), index=False)

In [14]:
df_train[columns_to_keep].to_csv(os.path.join(blob, "train.final_dataset.csv"), index=False)
df_test[columns_to_keep].to_csv(os.path.join(blob, "test.final_dataset.csv"), index=False)
df_test[columns_to_keep].to_csv(os.path.join(blob, "inference.final_dataset.csv"), index=False)

In [15]:
df_train.churn.value_counts()

0    690
1    347
Name: churn, dtype: int64